### ISSUE TITLE
Scrolling horizontally in diff view, gives no color

### ISSUE THREAD

**Issue by eanker** [preview-code/rite-evaluation#107]
When scrolling horizontally in a diff, the color is not displayed when that part was not visible in the first overview. See image below.

![image](https://cloud.githubusercontent.com/assets/5946438/15497454/21aa08e6-219b-11e6-8c4d-eac307a76b54.png)

**Comment by TimvdLippe** [comment]
This is behaving the same as on GitHub. Therefore I would make this a low priority.
