### ISSUE TITLE
Firebase automatically logs in, without clicking a button

### ISSUE THREAD

**Issue by TimvdLippe** [preview-code/rite-evaluation#183]

**Comment by TimvdLippe** [comment]
This is because `firebase-authentication` currently executes this in the [attached callback](https://github.com/preview-code/rite-evaluation/blob/master/src/ajax/firebase-authentication.html#L77). Instead, `rite-app` should handle this logic. I previously had fixed this, but regressed it later.

**Comment by txsmith** [comment]
`Firebase automatically logs in, without clicking a button`

Call me stupid, but why is this a problem?

**Comment by TimvdLippe** [comment]
When you open the homepage, Firebase would automatically log in and you would be redirected to the projects page. Instead, the user should click on either "Log in with GitHub" or "Log in with Bitbucket" and only then should Firebase start to login (to its correct oAuth provider). Now, by default only GitHub is possible resulting in really weird behavior.

**Comment by txsmith** [comment]
But when you are logged in, 99/100 times you do not want to see the home page. You'd want to go to the app directly and have the possibility to go to the home page either when you log out or explicitly choose to click `home`. 

Anyway automatically logging in is a minor feature and may be implemented later if we see fit to do so.
