### ISSUE TITLE
Show error when branch can not be merged, because no common anchestor

### ISSUE THREAD

**Issue by eanker** [preview-code/rite-evaluation#187]
In the frontend nothing is shown when a branch can not be merged:
![image](https://cloud.githubusercontent.com/assets/5946438/15706473/0beed5ae-27f4-11e6-8cc9-fc7cac1b2214.png)
When a branch was previously selected, the changes of that branch are shown.

Whilst the api call gives this:

![image](https://cloud.githubusercontent.com/assets/5946438/15706423/c99fb6b4-27f3-11e6-8bc4-a68212b2c4c1.png)

A message in the frontend might be nice, to communicate to the user what is wrong.

**Comment by TimvdLippe** [comment]
The error handling can be improved while also working on #112
