### ISSUE TITLE
Incorporate feedback from Alessandro

### ISSUE THREAD

**Issue by eanker** [preview-code/rite-evaluation#202]

**Comment by TimvdLippe** [comment]
Section 7.2 has been updated to explain the Polymer coding convention. Let's see what Alessandro does not agree on in our next meeting?

**Comment by eanker** [comment]
I have updated most of chapther 6, just a few things need to be done.

The report was send yesterday, so your updated 7.2 is not included.

**Comment by TimvdLippe** [comment]
table: rows with measurements. column with treatments. numbers in cells. the unit of measure in column.
the name of the row and a little description.

experimental protocol: how do you recruit people, are you going to train them, how long does it last,
is it at home or in lab, are you gonna record, are you gonna take notes

Search for: how to do experimental protocol.

bullet points of the tasks.

the type of changes is a threat of validity. By choosing changes, you limit the types.
population is very different for different open source projects

Improve reflection

**Comment by TimvdLippe** [comment]
All feedback has been processed and it is ready for review. Updated section 5.5 with the experimental protocol and added table 5.1 with all measurements, description and unit of measurement.
