### ISSUE TITLE
Groups are not synced on preview-code.com

### ISSUE THREAD

**Issue by txsmith** [preview-code/rite-evaluation#337]
See https://preview-code.com/projects/preview-code/test-github-integration/pulls/72/space

versus: https://localhost:5200/projects/preview-code/test-github-integration/pulls/72/space

**Comment by TimvdLippe** [comment]
It appears that the database disconnects when syncing. This was the previous issue you were encountering and it seems like the old fix did not work correctly.

**Comment by eanker** [comment]
I was unable to reproduce this, we should use the tool and see when it fails.
