### ISSUE TITLE
Reconsider Activity page

### ISSUE THREAD

**Issue by txsmith** [preview-code/rite-evaluation#362]
The Activity page currently does not offer any benefit. We should decide what to do with it.

**Comment by eanker** [comment]
We should make it as the initial idea we had or remove it.

I would be in favour of removing it, we can always bring it back in the intended form.
At the moment there are a lot of other things that have a higher priority than this, in my opinion.

**Comment by eanker** [comment]
There is decided to make a new activity page.
With the current features:
- [x] Readme
- [ ]  New branch pushed (like github)
- [x] Contributors

**Comment by txsmith** [comment]
Extraced #406
