### ISSUE TITLE
Running the latest unreleased web-component-tester

### ISSUE THREAD

**Issue by txsmith** [preview-code/rite-evaluation#400]
For some reason, all recent web-component-tester versions fail with an `express.use is not a function` error as explained in https://github.com/Polymer/web-component-tester/issues/373. This was fixed in https://github.com/Polymer/web-component-tester/pull/445, but this fix is not yet in any release of wct.

I would like CI to work, so we need to run the latest unreleased web-component-tester as it is right now on master.

I've tried to get this working locally by running:
 `npm install -g https://github.com/Polymer/web-component-tester/tarball/master`
`cd <npm-global-dir>/web-component-tester`
`npm install`
`npm run build`
`cd ~/preview-code/frontend`
`wct`

This runs the correct version of web-component-tester as expected. However, due to changes in this version (see https://github.com/Polymer/web-component-tester/blob/master/CHANGELOG.md) the tool keeps prompting me to `bower install web-component-tester --save-dev`. Which in turn allows me to only install the releases of wct that we cannot use becasue of the issue described above.

I've tried adding to `bower.json`:
```
"devDependencies": {
    "web-component-tester": "#master",
```
but this does not solve the issue. @TimvdLippe please help

**Comment by TimvdLippe** [comment]
You can now install 6.0.0-prerelease.4
