### ISSUE TITLE
Commit view hides text by default

### ISSUE THREAD

**Issue by txsmith** [preview-code/rite-evaluation#408]
When viewing the commits in a PR, the message is hidden unless you click on the commit

**Comment by eanker** [comment]
You mean that not the whole message is shown if it does not fit?

This was done intended so you do not have to click on all the commits to collapse them.
This ticket made me think, and we might want to add a button to collapse or non-collapse them all.

**Comment by txsmith** [comment]
This is what I mean:
![screenshot from 2017-02-13 14-41-28](https://cloud.githubusercontent.com/assets/5946422/22885630/834a18a4-f1fa-11e6-96ed-32c12b6d209e.png)
