### ISSUE TITLE
Projects with punctuation crash Firebase

### ISSUE THREAD

**Issue by TimvdLippe** [preview-code/rite-evaluation#448]
Example: 
![image](https://cloud.githubusercontent.com/assets/5948271/23210880/b3a8c160-f8ff-11e6-83ea-2cb5f3486410.png)

Happened for me at https://preview-code.com/projects/AreaFiftyLAN/reveal.js/activity

**Comment by eanker** [comment]
I have encoded the calls to firebase, so we do not get ```.``` anymore. 

Now we get 

```ENOENT: no such file or directory, stat '/home/eva/Documents/frontend/projects/AreaFiftyLAN/reveal.js/overview'``` in the webpage itself.



Where ```'/home/eva/Documents/frontend/``` is my local path to this repo (was serving local).
So, the period does break more inside our tool.

As this only happens in very specific cases, as the period is the only restriction of firebase that is not in github (only project names). 
We have to investigate this later on, but it's not a high priority.
