### ISSUE TITLE
When creating a pull request the branch selectors can overlap

### ISSUE THREAD

**Issue by TimvdLippe** [preview-code/rite-evaluation#449]
![image](https://cloud.githubusercontent.com/assets/5948271/23210938/ebce7972-f8ff-11e6-972b-95e7b37e24e5.png)

I think it would be more desirable to have them exclusively open, e.g. 1 at a time.

Also when the focus is lost inside the selector, the selector should hide. E.g. when the user clicks on a different part of the application, the dropdown hides.

**Comment by eanker** [comment]
I can't reproduce this, for me only 1 at a time opens.

**Comment by TimvdLippe** [comment]
Hm I am on a Windows computer right now and using the live version. I can reproduce the issue 100% of the time here.

1. Click on `master` dropdown
2. Click on `<select branch>` dropdown
3. Observe that 2 dropdowns are shown over each other.

**Comment by eanker** [comment]
I also used the live version and done the steps you told me.
I'll check on a windows pc then.
