### ISSUE TITLE
Usage of hashtag inside code blocks are transformed into issue references

### ISSUE THREAD

**Issue by TimvdLippe** [preview-code/rite-evaluation#49]
Discovered in #43. This is because the regex is not aware of its context.

**Comment by TimvdLippe** [comment]
We might be able to parse the code block firsts and substitute the hashtags with their corresponding escaped unicode character. Then we can also fix the syntax highlighting.

**Comment by txsmith** [comment]
This issue seems to be solved on master.

**Comment by TimvdLippe** [comment]
I can still reproduce this at http://localhost:5200/projects/Polymer/Polymer/pulls/3630/overview

**Comment by txsmith** [comment]
The master branch looks like this for me:
![screenshot from 2016-05-11 13 08 52](https://cloud.githubusercontent.com/assets/5946422/15179021/90c5e82a-1779-11e6-9df1-d92c52808c6e.png)

**Comment by eanker** [comment]
There no #'s are rendered. Because the # for fixes does not work too.
In my (up-to-date) master both #'s are rendered.

**Comment by txsmith** [comment]
Ah I see, so it's either all or nothing.
